DATA:
  NAME: "CityscapesDataset"
  ROOT_PATH: "data/objdet-datasets/Cityscapes"
  TRAIN_TRANSFORMS:
    LoadAnnotations: {}
    JointResize: {
      img_scale: [2048, 1024],
      ratio_range: [0.5, 2.0]}
    SegRandomCrop: {
      crop_size: [512, 1024],
      cat_max_ratio: 0.75}
    JointRandomFlip: {flip_ratio: 0.5}
    PhotoMetricDistortion: {}
    Normalize: {
      mean: [123.675, 116.28, 103.53], 
      std: [58.395, 57.12, 57.375], 
      to_rgb: False}
    Pad: {
      size: [512, 1024], 
      pad_val: 0, 
      seg_pad_val: 255}
    DefaultFormatBundle: {}
    Collect: {keys: ['img', 'gt_semantic_seg']}
  TEST_TRANSFORMS:
    MultiScaleFlipAug: {
      img_scale: [2048, 1024],
      flip: False,
      transforms: {
        JointResize: {keep_ratio: True},
        JointRandomFlip: {},
        Normalize: {
          mean: [123.675, 116.28, 103.53],
          std: [58.395, 57.12, 57.375]},
        ImageToTensor: {keys: ['img']},
        Collect: {keys: ['img']}
        }
      }
  TRAIN_DATA:
    TYPE: "Normal" # "Concat" "Repeat" "Balanced"
    FLAG: 1
    DATA_INFO: [["gtFine/train"]]
    DATA_PREFIX: ["leftImg8bit/train"]
    CLASS_NAMES: "CityscapesDataset"
    IS_TFRECORD: False
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  VAL_DATA:
    TYPE: "Normal"
    FLAG: 1
    DATA_INFO: [["gtFine/val"]]
    DATA_PREFIX: ["leftImg8bit/val"]
    CLASS_NAMES: "CityscapesDataset"
    IS_TFRECORD: False
    TEST_MODE: False
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  TEST_DATA:
    TYPE: "Normal"
    FLAG: 1
    DATA_INFO: [["gtFine/val"]]
    DATA_PREFIX: ["leftImg8bit/val"]
    CLASS_NAMES: "CityscapesDataset"
    IS_TFRECORD: False
    TEST_MODE: True
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
