MODEL:
  TYPE: 'seg'
  NAME: 'EncoderDecoder'
  PRETRAINED_MODEL_PATH: "meta/pretrained/swinv2_base_simmim_imagenet1k.pth"
  BACKBONE:
    type: "SwinTransformerV2"
    embed_dim: 128
    depths: [2, 2, 18, 2]
    num_heads: [4, 8, 16, 32]
    window_size: 7
    drop_path_rate: 0.5
    use_checkpoint: True
    out_indices: [0, 1, 2, 3]
  DECODE_HEAD:
    type: 'UPerHead'
    in_channels: [128, 256, 512, 1024]
    in_index: [0, 1, 2, 3]
    pool_scales: [1, 2, 3, 6]
    channels: 512
    dropout_ratio: 0.1
    num_classes: 150
    norm_cfg: {
      type: 'BN',
      requires_grad: True}
    align_corners: False
  AUXILIARY_HEAD:
    type: 'SegFCNHead'
    in_channels: 512
    in_index: 2
    channels: 256
    num_convs: 1
    concat_input: False
    dropout_ratio: 0.1
    num_classes: 150
    norm_cfg: {
      type: 'BN',
      requires_grad: True}
    align_corners: False
  LOSS:
    type: 'CrossEntropyLoss'
    use_sigmoid: False
    loss_weight: 1.0
  EXTEND_LOSS:
    type: 'CrossEntropyLoss'
    use_sigmoid: False
    loss_weight: 0.4
  TEST_CFG:
    mode: 'whole'