SCHEDULE:
  OPTIMIZER:
    type: "AdamW"
    lr: 0.001
    betas: [0.9, 0.999]
    weight_decay: 0.05
    layer_decay: 0.8
    model_type: "vit"
    model_depth: [12]
    PARAMWISE_CFG:
      custom_keys: [{}]
  OPTIMIZER_CONFIG:
    grad_clip: {
      max_norm: 5,
      norm_type: 2}
    fp16: True
  LR_POLICY:
    policy: "CosineAnnealing"
    by_epoch: False
    min_lr_ratio: 0.00125
    warmup: "linear"
    warmup_iters: 20
    warmup_ratio: 0.0002
    warmup_by_epoch: True
  RUNNER:
    type: "EpochBasedRunner"
    max_epochs: 100
