weights: runs/train/bottle_source_ResNet_SE4/weights/best.pt
cfg: models/bottle/bottle_source_ResNet_SE_CoT.yaml
name: bottle_source_ResNet_SE_CoT
data: data/bottle.yaml
hyp: data/hyps/hyp.scratch-med.yaml
epochs: 300
batch_size: 34
imgsz: 768
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: false
bucket: ''
cache: null
image_weights: false
device: 0,1
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 16
project: runs/train
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze: 0
save_period: 10
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/bottle_source_ResNet_SE_CoT7
