MODEL:
  BASE: "models/classifications/cls_vitb_linear.yaml"
  PRETRAINED_MODEL_PATH: "meta/pretrained/vit_base_emb_hvpmtl_tencentml_ep10.pth"  
DATA:
  BASE: "datasets/classifications/cls_imagenet_randaug.yaml"
  TRAIN_DATA:
    TYPE: "Concat" # "Concat" "Repeat" "Balanced"
    DATA_INFO: [['tfrecords/train*.tfrecord']] # "annotations/train.txt"
    SAMPLES_PER_DEVICE: 8
    WORKERS_PER_DEVICE: 8
  VAL_DATA:
    TYPE: "Normal"
    DATA_INFO: [['tfrecords/val*.tfrecord']] # "split_valid_tfrecord_0.0-944.20210505150928"
    SAMPLES_PER_DEVICE: 8
    WORKERS_PER_DEVICE: 8
  TEST_DATA:
    TYPE: "Normal"
    DATA_INFO: [['tfrecords/val*.tfrecord']] # "annotations/val.txt"
    SAMPLES_PER_DEVICE: 8
    WORKERS_PER_DEVICE: 8
SCHEDULE:
  BASE: "schedulers/schedule_adamw_ld.yaml"
  OPTIMIZER:
    type: "AdamW"
    lr: 0.00125
    betas: [0.9, 0.999]
    weight_decay: 0.05
    layer_decay: 0.65
    model_type: "vit"
    model_depth: [12]
    PARAMWISE_CFG:
      custom_keys: [{}]
  OPTIMIZER_CONFIG:
    grad_clip: {
      max_norm: 5,
      norm_type: 2}
    fp16: False
  LR_POLICY:
    policy: "CosineAnnealing"
    by_epoch: False
    min_lr_ratio: 0.0002
    warmup: "linear"
    warmup_iters: 20
    warmup_ratio: 0.0002
    warmup_by_epoch: True
RUNTIME:
  BASE: "runtimes/runtime_base.yaml"
  WORKFLOW: [['train', 1]]
