DATA:
  NAME: "CocoDataset"
  ROOT_PATH: "data/objdet-datasets/COCO"
  TRAIN_TRANSFORMS:
    MosaicPipeline: {
      individual_pipeline: {
        LoadAnnotations: {with_bbox: True},
        JointResize: {img_scale: [[640, 640]], keep_ratio: True}
      }, pad_val: 114}
    Albu: {
      update_pad_shape: True,
      skip_img_without_anno: False,
      bbox_params: {
        type: 'BboxParams',
        format: 'pascal_voc',
        min_area: 4,
        min_visibility: 0.2,
        label_fields: ['gt_labels'],
        check_each_transform: False},
      transforms: {
        PadIfNeeded: {
          min_height: 1920,
          min_width: 1920,
          border_mode: 0,
          value: [114, 114, 114],
          always_apply: True},
        RandomCrop: {
          width: 1280,
          height: 1280,
          always_apply: True},
        RandomScale: {
          scale_limit: 0.5,
          interpolation: 1,
          always_apply: True},
        CenterCrop: {
          width: 640,
          height: 640,
          always_apply: True},
        HorizontalFlip: {p: 0.5}}}
    HueSaturationValueJitter: {
      hue_ratio: 0.015,
      saturation_ratio: 0.7,
      value_ratio: 0.4}
    GtBBoxesFilter: {
      min_size: 2, 
      max_aspect_ratio: 20}
    Normalize: {
      mean: [114, 114, 114],
      std: [255, 255, 255],
      to_rgb: False}
    DefaultFormatBundle: {}
    Collect: {keys: ['img', 'gt_bboxes', 'gt_labels']}
  TEST_TRANSFORMS:
    MultiScaleFlipAug: {
      img_scale: [640, 640],
      flip: False,
      transforms: {
        JointResize: {keep_ratio: True},
        JointRandomFlip: {},
        Pad: {size_divisor: 32},
        Normalize: {
          mean: [114, 114, 114],
          std: [255, 255, 255],
          to_rgb: False},
        ImageToTensor: {keys: ['img']},
        Collect: {keys: ['img']}
        }
      }
  TRAIN_DATA:
    TYPE: "Repeat" # "Normal" "Concat" "Repeat" "Balanced"
    FLAG: 2
    #IMAGE_SIZE: [300, 300]
    DATA_INFO: [['tfrecords/train.tfrecord']] #[["annotations/instances_train2017.json"]]
    DATA_PREFIX: ["train2017/"]
    CLASS_NAMES: "CocoDataset"
    IS_TFRECORD: True
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  VAL_DATA:
    TYPE: "Normal"
    FLAG: 1
    #MIN_SIZE: 100
    DATA_INFO: [['tfrecords/val.tfrecord']] # [["annotations/instances_val2017.json"]]
    DATA_PREFIX: ["val2017/"]
    CLASS_NAMES: "CocoDataset"
    IS_TFRECORD: True
    TEST_MODE: False
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  TEST_DATA:
    TYPE: "Normal"
    FLAG: 1
    #MIN_SIZE: 100
    DATA_INFO: [['tfrecords/val.tfrecord']] # [["annotations/instances_val2017.json"]]
    DATA_PREFIX: ["val2017/"]
    CLASS_NAMES: "CocoDataset"
    IS_TFRECORD: True
    TEST_MODE: True
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
