DATA:
  NAME: "CocoDataset"
  ROOT_PATH: "data/objdet-datasets/COCO"
  TRAIN_TRANSFORMS:
    LoadAnnotations: {with_bbox: True}
    PhotoMetricDistortion: {}
    JointRandomFlip: {flip_ratio: 0.5}
    AutoAugment:
      policies: 
      - - {type: 'JointResize',
           img_scale: [[480, 1333], [512, 1333], [544, 1333], [576, 1333],
                      [608, 1333], [640, 1333], [672, 1333], [704, 1333],
                      [736, 1333], [768, 1333], [800, 1333]],
           multiscale_mode: 'value',
           keep_ratio: True}
      - - {type: 'JointResize',
           img_scale: [[400, 1333], [500, 1333], [600, 1333]],
           multiscale_mode: 'value',
           keep_ratio: True}
        - {type: 'JointRandomCrop',
           crop_type: 'absolute_range',
           crop_size: [384, 600],
           allow_negative_crop: True}
        - {type: 'JointResize',
           img_scale: [[480, 1333], [512, 1333], [544, 1333],
                       [576, 1333], [608, 1333], [640, 1333],
                       [672, 1333], [704, 1333], [736, 1333],
                       [768, 1333], [800, 1333]],
           multiscale_mode: 'value',
           override: True,
           keep_ratio: True}
    Normalize: {
      mean: [123.675, 116.28, 103.53],
      std: [58.395, 57.12, 57.375],
      to_rgb: False}
    Pad: {size_divisor: 32}
    DefaultFormatBundle: {}
    Collect: {keys: ['img', 'gt_bboxes', 'gt_labels']}
  TEST_TRANSFORMS:
    MultiScaleFlipAug: {
      img_scale: [1333, 800],
      flip: False,
      transforms: {
        JointResize: {keep_ratio: True},
        JointRandomFlip: {},
        Normalize: {
          mean: [123.675, 116.28, 103.53],
          std: [58.395, 57.12, 57.375],
          to_rgb: False},
        Pad: {size_divisor: 32},
        ImageToTensor: {keys: ['img']},
        Collect: {keys: ['img']}
        }
      }  
  TRAIN_DATA:
    TYPE: "Repeat" # "Normal" "Concat" "Repeat" "Balanced"
    FLAG: 2
    #IMAGE_SIZE: [300, 300]
    DATA_INFO: [["annotations/instances_train2017.json"]]
    DATA_PREFIX: ["train2017/"]
    CLASS_NAMES: "CocoDataset"
    IS_TFRECORD: False
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  VAL_DATA:
    TYPE: "Normal"
    FLAG: 1
    #MIN_SIZE: 100
    DATA_INFO: [["annotations/instances_val2017.json"]]
    DATA_PREFIX: ["val2017/"]
    CLASS_NAMES: "CocoDataset"
    IS_TFRECORD: False
    TEST_MODE: False
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  TEST_DATA:
    TYPE: "Normal"
    FLAG: 1
    #MIN_SIZE: 100
    DATA_INFO: [["annotations/instances_val2017.json"]]
    DATA_PREFIX: ["val2017/"]
    CLASS_NAMES: "CocoDataset"
    IS_TFRECORD: False
    TEST_MODE: True
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
