DATA:
  NAME: "CocoDataset"
  ROOT_PATH: "data/objdet-datasets/COCO"
  TRAIN_TRANSFORMS:
    LoadAnnotations: {with_bbox: True}
    PhotoMetricDistortion: {}
    Expand: {
      mean: [0, 0, 0],
      to_rgb: False,
      ratio_range: [1, 2]}
    MinIoURandomCrop: {
      min_ious: [0.1, 0.3, 0.5, 0.7, 0.9],
      min_crop_size: 0.3}
    JointResize: {
      img_scale: [[1333, 800]],
      keep_ratio: True}
    JointRandomFlip: {flip_ratio: 0.5}
    Normalize: {
      mean: [0, 0, 0],
      std: [255, 255, 255],
      to_rgb: False}
    Pad: {size_divisor: 32, pad_val: [0.447, 0.447, 0.447]}
    DefaultFormatBundle: {}
    Collect: {keys: ['img', 'gt_bboxes', 'gt_labels']}
  TEST_TRANSFORMS:
    MultiScaleFlipAug: {
      img_scale: [1333, 800],
      flip: False,
      transforms: {
        JointResize: {keep_ratio: True},
        Normalize: {
          mean: [0, 0, 0],
          std: [255, 255, 255],
          to_rgb: False},
        Pad: {size_divisor: 32, pad_val: [0.447, 0.447, 0.447]},
        ImageToTensor: {keys: ['img']},
        Collect: {keys: ['img']}
      }
    }
  TRAIN_DATA:
    TYPE: "Concat" # "Normal" "Repeat" "Balanced"
    FLAG: 1
    DATA_INFO: [['tfrecords/train.tfrecord']]
    DATA_PREFIX: ["train2017/"]
    CLASS_NAMES: "CocoDataset"
    IS_TFRECORD: False
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  VAL_DATA:
    TYPE: "Concat" # "Normal" "Repeat" "Balanced"
    FLAG: 1
    DATA_INFO: [['tfrecords/val.tfrecord']]
    DATA_PREFIX: ["val2017/"]
    CLASS_NAMES: "CocoDataset"
    IS_TFRECORD: False
    TEST_MODE: False
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  TEST_DATA:
    TYPE: "Concat" # "Repeat" "Balanced"
    FLAG: 1
    DATA_INFO: [["tfrecords/val.tfrecord"]]
    DATA_PREFIX: ["val2017/"]
    CLASS_NAMES: "CocoDataset"
    IS_TFRECORD: False
    TEST_MODE: True
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
