DATA:
  NAME: "VOCDataset"
  ROOT_PATH: "/workspace/data/VOCdevkit"
  TRAIN_TRANSFORMS:
    LoadAnnotations: {with_bbox: True}
    JointResize: {
      img_scale: [[1333, 800]],
      keep_ratio: True}
    JointRandomFlip: {flip_ratio: 0.5}
    Normalize: {
      mean: [123.675, 116.28, 103.53],
      std: [58.395, 57.12, 57.375],
      to_rgb: False}
    Pad: {size_divisor: 32}
    DefaultFormatBundle: {}
    Collect: {keys: ['img', 'gt_bboxes', 'gt_labels']}
  TEST_TRANSFORMS:
    MultiScaleFlipAug: {
      img_scale: [1333, 800],
      flip: False,
      transforms: {
        JointResize: {keep_ratio: True},
        JointRandomFlip: {},
        Normalize: {
          mean: [123.675, 116.28, 103.53],
          std: [58.395, 57.12, 57.375],
          to_rgb: False},
        Pad: {size_divisor: 32},
        ImageToTensor: {keys: ['img']},
        Collect: {keys: ['img']}
      }
    }
  TRAIN_DATA:
    TYPE: "Concat" # "Normal" "Repeat" "Balanced"
    FLAG: 1
    # IMAGE_SIZE: [300, 300]
    DATA_INFO: [['tfrecords/train*.tfrecord']] # [["VOC2007/ImageSets/Main/train.txt"], ["VOC2012/ImageSets/Main/train.txt"]]
    DATA_PREFIX: ["VOC2007/", "VOC2012/"]
    CLASS_NAMES: "VOCDataset"
    IS_TFRECORD: False
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  VAL_DATA:
    TYPE: "Concat" # "Normal" "Repeat" "Balanced"
    FLAG: 1
    # MIN_SIZE: 100
    DATA_INFO: [['tfrecords/val*.tfrecord']] # [["VOC2007/ImageSets/Main/val.txt"], ["VOC2012/ImageSets/Main/val.txt"]]
    DATA_PREFIX: ["VOC2007/", "VOC2012/"]
    CLASS_NAMES: "VOCDataset"
    IS_TFRECORD: False
    TEST_MODE: False
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  TEST_DATA:
    TYPE: "Concat" # "Repeat" "Balanced"
    FLAG: 1
    # MIN_SIZE: 100
    DATA_INFO: [['tfrecords/val*.tfrecord']] # [["VOC2007/ImageSets/Main/val.txt"], ["VOC2012/ImageSets/Main/val.txt"]]
    DATA_PREFIX: ["VOC2007/", "VOC2012/"]
    CLASS_NAMES: "VOCDataset"
    IS_TFRECORD: False
    TEST_MODE: True
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
