DATA:
  NAME: "SslClsPretrainDataset"
  ROOT_PATH: "data/objcls-datasets/ImageNet/imagenet1k"
  TRAIN_TRANSFORMS:
    MultiApplyDINO:
      policies:
      - - {type: 'ImgRandomResizedCrop',
           size: 224,
           scale: [0.4, 1.0]}
        - {type: 'ImgRandomFlip',
           flip_prob: 0.5,
           direction: 'horizontal'}
        - {type: 'RandomApply',
           policies: [{
             type: 'PhotoMetricDistortion',
             brightness_delta: 64,
             contrast_range: [0.4, 1.4],
             saturation_range: [0.2, 1.2],
             hue_delta: 16}],
           p: 0.8}
        - {type: 'RandomGrayscale',
           gray_prob: 0.2}
        - {type: 'GaussianBlur',
           sigma: [.1, 5.]}
        - {type: 'Normalize',
           mean: [123.675, 116.28, 103.53], 
           std: [58.395, 57.12, 57.375], 
           to_rgb: False}
      - - {type: 'ImgRandomResizedCrop',
           size: 224,
           scale: [0.4, 1.0]}
        - {type: 'ImgRandomFlip',
           flip_prob: 0.5,
           direction: 'horizontal'}
        - {type: 'RandomApply',
           policies: [{
             type: 'PhotoMetricDistortion',
             brightness_delta: 64,
             contrast_range: [0.4, 1.4],
             saturation_range: [0.2, 1.2],
             hue_delta: 16}],
           p: 0.8}
        - {type: 'RandomGrayscale',
           gray_prob: 0.2}
        - {type: 'RandomApply',
           policies: [{
             type: 'GaussianBlur',
             sigma: [.1, 5.]}],
           p: 0.1}
        - {type: 'Solarization',
           p: 0.2}
        - {type: 'Normalize',
           mean: [123.675, 116.28, 103.53], 
           std: [58.395, 57.12, 57.375], 
           to_rgb: False}
      - - {type: 'ImgRandomResizedCrop',
           size: 96,
           scale: [0.4, 1.0]}
        - {type: 'ImgRandomFlip',
           flip_prob: 0.5,
           direction: 'horizontal'}
        - {type: 'RandomApply',
           policies: [{
             type: 'PhotoMetricDistortion',
             brightness_delta: 64,
             contrast_range: [0.4, 1.4],
             saturation_range: [0.2, 1.2],
             hue_delta: 16}],
           p: 0.8}
        - {type: 'RandomGrayscale',
           gray_prob: 0.2}
        - {type: 'RandomApply',
           policies: [{
             type: 'GaussianBlur',
             sigma: [.1, 5.]}],
           p: 0.1}
        - {type: 'Normalize',
           mean: [123.675, 116.28, 103.53], 
           std: [58.395, 57.12, 57.375], 
           to_rgb: False}
      local_crops_number: 2
    DefaultFormatBundle: {}
    ClsCollect: {keys: ['img', 'img_k', 'img_s', 'gt_label']}
  TEST_TRANSFORMS:
    ImgResize: {
      size: [256, -1]
      }
    ImgCenterCrop: {
      size: [224, 224]
      }
    Normalize: {
      mean: [123.675, 116.28, 103.53], 
      std: [58.395, 57.12, 57.375], 
      to_rgb: False}
    ImageToTensor: {keys: ['img']}
    ClsCollect: {keys: ['img']}
  TRAIN_DATA:
    TYPE: "Concat"
    FLAG: 1
    DATA_INFO: [['tfrecords/train*.tfrecord']]
    DATA_PREFIX: ["images"]
    IS_TFRECORD: True
    VAL_MODE: False
    TEST_MODE: False
    SAMPLES_PER_DEVICE: 8
    WORKERS_PER_DEVICE: 8
  VAL_DATA:
    TYPE: "Normal"
    FLAG: 1
    DATA_INFO: [['tfrecords/val*.tfrecord']]
    DATA_PREFIX: ["images"]
    IS_TFRECORD: True
    VAL_MODE: True
    TEST_MODE: False
    SAMPLES_PER_DEVICE: 8
    WORKERS_PER_DEVICE: 8
  TEST_DATA:
    TYPE: "Normal"
    FLAG: 1
    DATA_INFO: [['tfrecords/val*.tfrecord']]
    DATA_PREFIX: ["images"]
    IS_TFRECORD: True
    VAL_MODE: False
    TEST_MODE: True
    SAMPLES_PER_DEVICE: 8
    WORKERS_PER_DEVICE: 8
