'label_dict':
  1: 'yise'
  2: 'baisezaodian'
  3: 'shuiyin'
  4: 'guashang'
  5: 'cashang'
  6: 'heidian'
  7: 'shahenyin'
  8: 'yiwu'
  9: 'daowen'
  10: 'huashang'
  11: 'penshabujun'
  12: 'aohen'
  13: 'tuhaohen'
  14: 'aotuhen'
  15: 'aokeng'
  16: 'mian'
  17: 'qingweimianhua'
  18: 'qita'
  19: 'pengshang'
  20: 'pengshang'
  21: 'huanxingdaowen'
  22: 'daowenxian'
  23: 'tabian'
  27: 'pengshang'

'task_id': 'TaskID'
'product_sn': 'ProductSN'
'picture_id': 'PictureID'
'label': 'ProductGradeCode'
'x_min': 'PointX'
'y_min': 'PointY'
'box_width': 'Width'
'box_height': 'Height'