MODEL:
  TYPE: "cls"
  NAME: "ImageClassifier"
  PRETRAINED_MODEL_PATH: ""
  BACKBONE:
    type: "SwinTransformerV2"
    embed_dim: 352
    depths: [2, 2, 18, 2]
    num_heads: [11, 22, 44, 88]
    window_size: 24
    drop_path_rate: 0.5
    use_checkpoint: True
    out_indices: [3]
  NECK:
    type: "GlobalAveragePooling"
  CLS_HEAD:
    type: "LinearClsHead"
    num_classes: 1000
    in_channels: 2816
  LOSS:
    type: 'LabelSmoothLoss'
    label_smooth_val: 0.1
    mode: 'original'
    loss_weight: 1.0
  EXTEND:
    with_rdrop: False
    topk: [1, 5]
  TRAIN_CFG:
    augmentor:
    - {type: 'BatchCutMix',
       alpha: 1.0,
       num_classes: 1000,
       prob: 0.5}
  