MODEL:
  TYPE: "cls"
  NAME: "ImageClassifier"
  PRETRAINED_MODEL_PATH: ""
  BACKBONE:
    type: "SwinTransformer"
    embed_dim: 96
    depths: [2, 2, 6, 2]
    num_heads: [3, 6, 12, 24]
    out_indices: [3]
  NECK:
    type: "GlobalAveragePooling"
  CLS_HEAD:
    type: "MultilabelClsHead"
    num_classes: 19985
    in_channels: 768
  LOSS:
    type: 'SigmoidBCELoss'
    loss_weight: 1.0
