MODEL:
  BASE: "models/detections/det_atss_swinbv2_dyhead.yaml"
  PRETRAINED_MODEL_PATH: "meta/pretrained/swinv2_pretrained_simmim_imagenet1k.pth"
  BACKBONE:
    use_checkpoint: False
  BBOX_HEAD:
    type: 'ATSSHead'
    num_classes: 65
DATA:
  BASE: "datasets/detections/det_multiobj.yaml"
  TRAIN_TRANSFORMS:
    JointResize: {
      img_scale: [[416, 416]],
      keep_ratio: True}
  TRAIN_DATA:
    DATA_INFO: [['tfrecords/train_*.tfrecord']]
    IS_TFRECORD: True
    SAMPLES_PER_DEVICE: 2
    WORKERS_PER_DEVICE: 2
  VAL_DATA:
    DATA_INFO: [['tfrecords/val.tfrecord']]
    IS_TFRECORD: True
    SAMPLES_PER_DEVICE: 8
    WORKERS_PER_DEVICE: 8
  TEST_DATA:
    DATA_INFO: [['tfrecords/val.tfrecord']]
    IS_TFRECORD: True
    SAMPLES_PER_DEVICE: 8
    WORKERS_PER_DEVICE: 8
SCHEDULE:
  BASE: "schedulers/schedule_1x.yaml"
  OPTIMIZER:
    type: "SGD"
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0001
RUNTIME:
  BASE: "runtimes/runtime_base.yaml"
  FIND_UNUSED_PARAMETERS: True
