MODEL:
  BASE: "models/detections/det_yolov4s_cspdarknet.yaml"
  BBOX_HEAD:
    num_classes: 65
DATA:
  BASE: "datasets/detections/det_multiobj_yolo.yaml"
  ROOT_PATH: "data/objdet-datasets/MultiObjDet"
  TRAIN_DATA:
    DATA_INFO: [['tfrecords/train_*.tfrecord']]
    IS_TFRECORD: True
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  VAL_DATA:
    DATA_INFO: [['tfrecords/val.tfrecord']]
    IS_TFRECORD: True
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  TEST_DATA:
    DATA_INFO: [['tfrecords/val.tfrecord']]
    IS_TFRECORD: True
    SAMPLES_PER_DEVICE: 1
    WORKERS_PER_DEVICE: 1
SCHEDULE:
  BASE: "schedulers/schedule_yolo.yaml"
  OPTIMIZER:
    lr: 0.001
  LR_POLICY:
    warmup_iters: 5000
    warmup_ratio: 0.001
    step: [66, 92]
RUNTIME:
  BASE: "runtimes/runtime_base.yaml"
