weights: /home/zhang/defect_detection/yolov5/runs/train/exp61/weights/best.pt
teacher: weights/yolov5s.pt
distill_ratio: 0.5
t_conf_thres: 0.1
t_nms_thres: 0.3
full_output_loss: false
cfg: /home/zhang/defect_detection/yolov5/models/exp/exp61.yaml
data: data/PCB_Color.yaml
hyp: data/hyp_distill.scratch.yaml
epochs: 30
batch_size: 1
img_size:
- 1280
- 1280
rect: false
resume: false
nosave: false
notest: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: cpu
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 0
project: runs/train
entity: null
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
world_size: 1
global_rank: -1
save_dir: runs/train/exp2
total_batch_size: 1
