MODEL:
  TYPE: "det"
  NAME: "DETR"
  PRETRAINED_MODEL_PATH: ""
  BACKBONE:
    type: "SwinTransformerV2"
    embed_dim: 128
    depths: [2, 2, 18, 2]
    num_heads: [4, 8, 16, 32]
    window_size: 7
    drop_path_rate: 0.2
    use_checkpoint: True
    out_indices: [3]
  NECK:
    type: 'TransformerNeck'
    in_channels: 1024
    transformer: {
      type: 'DETRTransformer',
      encoder: {
        type: 'DETRTransformerEncoder',
        num_layers: 6,
        transformerlayers: {
          type: 'BaseTransformerLayer',
          attn_cfgs: [
            {
              type: 'MultiheadAttention',
              embed_dims: 256,
              num_heads: 8,
              dropout: 0.1
            }
          ],
          feedforward_channels: 2048,
          ffn_dropout: 0.1,
          operation_order: ['self_attn', 'norm', 'ffn', 'norm'],
        }
      },
      decoder: {
        type: 'DETRTransformerDecoder',
        return_intermediate: True,
        num_layers: 6,
        transformerlayers: {
          type: 'DETRTransformerDecoderLayer',
          attn_cfgs: {
            type: 'MultiheadAttention',
            embed_dims: 256,
            num_heads: 8,
            dropout: 0.1
          },
          feedforward_channels: 2048,
          ffn_dropout: 0.1,
          operation_order: ['self_attn', 'norm', 'cross_attn', 'norm', 'ffn', 'norm']
        }
      }
    }  
    positional_encoding: {
      type: 'SinePositionalEncoding',
      num_feats: 128,
      normalize: True
    }
  BBOX_HEAD:
    type: 'DETRHead'
    num_classes: 80
    embed_dims: 256
    loss_cls: {
      type: 'CrossEntropyLoss',
      bg_cls_weight: 0.1,
      use_sigmoid: False,
      loss_weight: 1.0,
      class_weight: 1.0
    }
    loss_bbox: {type: 'L1Loss', loss_weight: 5.0}
    loss_iou: {type: 'GIoULoss', loss_weight: 2.0}
  TRAIN_CFG:
    assigner: {
      type: 'HungarianAssigner',
      cls_cost: {type: 'ClassificationCost', weight: 1.},
      reg_cost: {type: 'BBoxL1Cost', weight: 5.0, box_format: 'xywh'},
      iou_cost: {type: 'IoUCost', iou_mode: 'giou', weight: 2.0}}
    allowed_border: -1
    pos_weight: -1
    debug: False
  TEST_CFG:
    max_per_img: 100
