MODEL:
  TYPE: "det"
  NAME: "ATSS"
  PRETRAINED_MODEL_PATH: ""
  BACKBONE:
    type: "SwinTransformerV2"
    embed_dim: 128
    depths: [2, 2, 18, 2]
    num_heads: [4, 8, 16, 32]
    window_size: 7
    drop_path_rate: 0.2
    use_checkpoint: True
    out_indices: [0, 1, 2, 3]
  NECK:
  - {type: 'FPN',
     in_channels: [128, 256, 512, 1024],
     out_channels: 256,
     start_level: 1,
     add_extra_convs: 'on_output',
     num_outs: 5}
  - {type: 'DyHead', 
     in_channels: 256,
     out_channels: 256,
     num_blocks: 6}
  BBOX_HEAD:
    type: 'ATSSHead'
    num_classes: 80
    in_channels: 256
    cls_stacked_convs: 0
    reg_stacked_convs: 0
    feat_channels: 256
    anchor_generator: {
      type: 'AnchorGenerator',
      ratios: [1.0],
      octave_base_scale: 8,
      scales_per_octave: 1,
      strides: [8, 16, 32, 64, 128]}
    bbox_coder: {
      type: 'DeltaXYWHBBoxCoder',
      target_means: [.0, .0, .0, .0],
      target_stds: [0.1, 0.1, 0.2, 0.2]}
    loss_cls: {
      type: 'FocalLoss',
      use_sigmoid: True,
      gamma: 2.0,
      alpha: 0.25,
      loss_weight: 1.0}
    loss_bbox: {type: 'GIoULoss', loss_weight: 2.0}
    loss_centerness: {
      type: 'CrossEntropyLoss',
      use_sigmoid: True,
      loss_weight: 1.0}
  TRAIN_CFG:
    assigner: {type: 'ATSSAssigner', topk: 9}
    allowed_border: -1
    pos_weight: -1
    debug: False
  TEST_CFG:
    nms_pre: 1000
    min_bbox_size: 0
    score_thr: 0.05
    nms: {type: 'common_nms', iou_threshold: 0.6}
    max_per_img: 100
