MODEL:
  BASE: "models/detections/det_fasterrcnn_r50_fpn.yaml"
  PRETRAINED_MODEL_PATH: ""
  ROI_HEAD:
    bbox_head:
      num_classes: 80
DATA:
  BASE: "datasets/detections/det_coco.yaml"
  TRAIN_TRANSFORMS:
    LoadAnnotations: {with_bbox: True, with_mask: False}
    JointResize: {
      img_scale: [[640, 640]], 
      keep_ratio: True}
    Collect: {keys: ['img', 'gt_bboxes', 'gt_labels']}
  TRAIN_DATA:
    SAMPLES_PER_DEVICE: 2
    WORKERS_PER_DEVICE: 2
  VAL_DATA:
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  TEST_DATA:
    SAMPLES_PER_DEVICE: 1
    WORKERS_PER_DEVICE: 1
SCHEDULE:
  BASE: "schedulers/schedule_2x.yaml"
  OPTIMIZER: 
    lr: 0.01
RUNTIME:
  BASE: "runtimes/runtime_base.yaml"
