MODEL:
  BASE: "models/detections/det_maskrcnn_swinb_fpn.yaml"
  PRETRAINED_MODEL_PATH: "meta/pretrained/swin_base_emb_hvpmtl_tencentml_ep10.pth"
DATA:
  BASE: "datasets/detections/det_coco.yaml"
  TRAIN_TRANSFORMS:
    JointResize: {
      img_scale: [[416, 416]], 
      keep_ratio: True}
  TRAIN_DATA:
    TYPE: "Concat"
    DATA_INFO: [["annotations/instances_train2017.json"]]
    IS_TFRECORD: False
    SAMPLES_PER_DEVICE: 2
    WORKERS_PER_DEVICE: 2
  VAL_DATA:
    DATA_INFO: [["annotations/instances_val2017.json"]]
    IS_TFRECORD: False
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  TEST_DATA:
    DATA_INFO: [["annotations/instances_val2017.json"]]
    IS_TFRECORD: False
    SAMPLES_PER_DEVICE: 1
    WORKERS_PER_DEVICE: 1
SCHEDULE:
  BASE: "schedulers/schedule_1x.yaml"
RUNTIME:
  BASE: "runtimes/runtime_base.yaml"
  CHECKPOINT_CONFIG:
    interval: 20
    by_epoch: True
