MODEL:
  BASE: "models/detections/det_yolov7_basic.yaml"
  PRETRAINED_MODEL_PATH: ""
  BBOX_HEAD:
    num_classes: 80
DATA:
  BASE: "datasets/detections/det_coco_yolo.yaml"
  TRAIN_TRANSFORMS:
    LoadAnnotations: {with_bbox: True}
    JointResize: {
      img_scale: [[640, 640]],
      keep_ratio: True}
    Collect: {keys: ['img', 'gt_bboxes', 'gt_labels']}
  TEST_TRANSFORMS:
    MultiScaleFlipAug: {
      img_scale: [640, 640],
    }
  TRAIN_DATA:
    DATA_INFO: [['tfrecords/train*.tfrecord']]
    IS_TFRECORD: True
    SAMPLES_PER_DEVICE: 4
    WORKERS_PER_DEVICE: 4
  VAL_DATA:
    DATA_INFO: [['tfrecords/val*.tfrecord']]
    IS_TFRECORD: True
    SAMPLES_PER_DEVICE: 1
    WORKERS_PER_DEVICE: 1
  TEST_DATA:
    DATA_INFO: [['tfrecords/val*.tfrecord']]
    IS_TFRECORD: True
    SAMPLES_PER_DEVICE: 1
    WORKERS_PER_DEVICE: 1
SCHEDULE:
  BASE: "schedulers/schedule_adamw.yaml"
  OPTIMIZER:
    type: "AdamW"
    lr: 0.001
    weight_decay: 0.0005
  OPTIMIZER_CONFIG:
    fp16: True
  LR_POLICY:
    policy: "CosineAnnealing"
    min_lr_ratio: 0.001
    warmup: "linear"
    warmup_iters: 1000
    warmup_ratio: 0.008
  RUNNER:
    type: "EpochBasedRunner"
    max_epochs: 100
RUNTIME:
  BASE: "runtimes/runtime_eval.yaml"
  CHECKPOINT_CONFIG:
    interval: 1
    by_epoch: True
    max_keep_ckpts: 20
  WORKFLOW: [['train', 1]]
  EVALUATION: [{metric: 'map', interval: 10}]
  STATIC_GRAPH: True
  # BASE: "runtimes/runtime_base.yaml"
  # STATIC_GRAPH: True
  # FIND_UNUSED_PARAMETERS: False
